install:
	cp com.keyfu.plist ~/Library/LaunchAgents/com.keyfu.plist
	launchctl load ~/Library/LaunchAgents/com.keyfu.plist
	launchctl start com.keyfu

uninstall:
	launchctl unload ~/Library/LaunchAgents/com.keyfu.plist
